apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
  namespace: talentflow
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc:5432/jobdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: talentflow
  labels:
    app: job-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: job-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: job-service
          image: ghcr.io/GITHUB_OWNER/talentflow/job-service:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: job-service-config
            - secretRef:
                name: job-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: talentflow
  labels:
    app: job-service
spec:
  selector:
    app: job-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
